# Shared helpers, sourced from the repository root.
MODULES="uniwill-laptop ite8291-mono ite8233-lightbar copilot-rctrl"

require_root() {
	[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo)" >&2; exit 1; }
}

# dkms_field <KEY> -> value from the top-level dkms.conf
dkms_field() {
	sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p" dkms.conf
}

DKMS_NAME=$(dkms_field PACKAGE_NAME)
DKMS_VERSION=$(dkms_field PACKAGE_VERSION)

# Remove the recoil16 DKMS package and the per-module packages of older versions.
dkms_remove_all() {
	for pkg in "$DKMS_NAME" ite8291-mono ite8233-lightbar copilot-rctrl uniwill-laptop-pcs; do
		for ver in $(dkms status "$pkg" 2>/dev/null | sed -n "s|^$pkg/\([^,:]*\).*|\1|p" | sort -u); do
			dkms remove "$pkg/$ver" --all >/dev/null 2>&1 || true
			rm -rf "/usr/src/$pkg-$ver"
		done
	done
}

# Man pages and shell completions generated by recoil16ctl: install_ctl_extras <binary> <share dir>
install_ctl_extras() {
	mkdir -p "$2/man/man1" "$2/bash-completion/completions" "$2/zsh/site-functions" "$2/fish/vendor_completions.d"
	"$1" man "$2/man/man1"
	install -Dm644 man/recoil16.7 -t "$2/man/man7/"
	"$1" completions bash > "$2/bash-completion/completions/recoil16ctl"
	"$1" completions zsh > "$2/zsh/site-functions/_recoil16ctl"
	"$1" completions fish > "$2/fish/vendor_completions.d/recoil16ctl.fish"
}

remove_ctl_extras() {
	rm -f "$1"/man/man1/recoil16ctl*.1 "$1/man/man7/recoil16.7" "$1/bash-completion/completions/recoil16ctl" \
	      "$1/zsh/site-functions/_recoil16ctl" "$1/fish/vendor_completions.d/recoil16ctl.fish"
}

# Helper scripts replaced by recoil16ctl
remove_old_commands() {
	rm -f /usr/local/bin/recoil16-rotate-screen /usr/local/bin/recoil16-set-charge-limit \
	      /usr/local/bin/recoil16-lightbar
}

# Restart KDE's power daemon for the desktop user: PowerDevil 6.7 crashes on a
# keyboard brightness key if the backlight LED appeared after it started.
restart_powerdevil() {
	user="${SUDO_USER:-}"
	[ -n "$user" ] || return 0
	systemctl --user -M "$user@" try-restart plasma-powerdevil.service >/dev/null 2>&1 || true
}
